# Generated by Django 3.2.9 on 2022-01-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reddit_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
