# Generated by Django 3.2.9 on 2022-01-04 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Memes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('tags', models.ManyToManyField(to='Memes.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('body', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Memes.meme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote', models.CharField(choices=[('up', 'Up vote'), ('down', 'Down vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Memes.meme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
            options={
                'unique_together': {('owner', 'meme')},
            },
        ),
    ]
