# Generated by Django 3.2.9 on 2022-01-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='meme',
            name='votes_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='votes_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
